# Generated by Django 5.2.8 on 2025-11-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва предмета')),
                ('short_name', models.CharField(blank=True, max_length=30, verbose_name='Коротка назва')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, 'Пʼятниця'), (5, 'Субота'), (6, 'Неділя')], verbose_name='День тижня')),
                ('start_time', models.TimeField(verbose_name='Початок')),
                ('end_time', models.TimeField(verbose_name='Кінець')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Аудиторія')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Викладач')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекція'), ('practice', 'Практика'), ('lab', 'Лабораторна'), ('other', 'Інше')], default='lecture', max_length=20, verbose_name='Тип заняття')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Заняття',
                'ordering': ['weekday', 'start_time'],
            },
        ),
    ]
