# Generated by Django 5.2.8 on 2025-11-29 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Завдання')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('due_date', models.DateField(verbose_name='Термін здачі')),
                ('is_done', models.BooleanField(default=False, verbose_name='Виконано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='diary.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Домашнє завдання',
                'verbose_name_plural': 'Домашні завдання',
                'ordering': ['due_date'],
            },
        ),
    ]
